import { useEffect, useRef, useState } from 'react'
import type React from 'react'
import { Camera, X } from 'lucide-react'

export function CameraCapture({ photos, setPhotos }: { photos: Blob[]; setPhotos: (photos: Blob[]) => void }) {
  const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream | null>(null); const [active, setActive] = useState(false); const [cameraError, setCameraError] = useState('')
  const start = async () => { try { streamRef.current = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'user', width: { ideal: 1280 }, height: { ideal: 720 } }, audio: false }); setActive(true); setCameraError('') } catch { setCameraError('Camera permission is required for enrollment.') } }
  const stop = () => { streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null; setActive(false) }
  const capture = () => { const video = videoRef.current; if (!video || !video.videoWidth || photos.length >= 3) return; const canvas = document.createElement('canvas'); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext('2d')?.drawImage(video, 0, 0); canvas.toBlob((blob) => blob && setPhotos([...photos, blob]), 'image/jpeg', .9) }
  const upload = (event: React.ChangeEvent<HTMLInputElement>) => { const selected = Array.from(event.target.files ?? []).filter((file) => file.type === 'image/jpeg' || file.type === 'image/png'); setPhotos([...photos, ...selected].slice(0, 3)); event.target.value = '' }
  useEffect(() => { if (active && videoRef.current && streamRef.current) videoRef.current.srcObject = streamRef.current }, [active])
  useEffect(() => () => { streamRef.current?.getTracks().forEach((track) => track.stop()) }, [])
  return <div className="space-y-3"><div className="relative aspect-video min-h-64 overflow-hidden rounded-lg bg-[#edf1ed] sm:min-h-80 lg:aspect-[16/8] lg:min-h-[360px]">{active ? <video ref={videoRef} autoPlay playsInline muted className="size-full object-cover" /> : <div className="grid size-full place-items-center text-center text-sm text-[var(--muted)]"><div><Camera size={28} className="mx-auto mb-2" />Use the camera or upload three reference images</div></div>}{active && <button type="button" title="Capture photo" onClick={capture} disabled={photos.length >= 3} className="absolute bottom-4 left-1/2 grid size-14 -translate-x-1/2 place-items-center rounded-full border-4 border-white bg-[var(--green)] text-white shadow-lg disabled:opacity-40"><Camera size={22} /></button>}</div><div className="flex flex-wrap items-center justify-between gap-3 text-sm"><span className="tabular font-semibold text-[var(--muted)]">{photos.length}/3 captured</span><div className="flex items-center gap-4">{active ? <button type="button" onClick={stop} className="font-bold text-[var(--red)]">Stop camera</button> : <button type="button" onClick={start} disabled={photos.length >= 3} className="font-bold text-[var(--green)] disabled:opacity-40">Start camera</button>}<label className="cursor-pointer font-bold text-[var(--green)] hover:underline">Upload images<input type="file" accept="image/jpeg,image/png" multiple onChange={upload} disabled={photos.length >= 3} className="sr-only" /></label></div></div>{cameraError && <p className="text-[11px] text-[var(--red)]">{cameraError}</p>}<p className="text-xs text-[var(--muted)]">Use either method, or combine them. Exactly three JPEG/PNG images are required.</p>{photos.length > 0 && <div className="flex flex-wrap gap-2">{photos.map((photo, index) => <button type="button" title={`Remove capture ${index + 1}`} key={index} onClick={() => setPhotos(photos.filter((_, photoIndex) => photoIndex !== index))} className="group relative"><img src={URL.createObjectURL(photo)} className="size-16 rounded-md object-cover ring-1 ring-[var(--line)]" alt={`Reference ${index + 1}`} /><span className="absolute inset-0 hidden place-items-center rounded-md bg-black/50 text-white group-hover:grid"><X size={14} /></span></button>)}</div>}</div>
}
